// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TC41InsertNameandreceiveatleastOneSuggestionTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC41InsertNameandreceiveatleastOneSuggestion() {
    driver.get("http://localhost:8080/VORWERK/RegisteredAccountController?action=dispatchRobot");
    driver.manage().window().setSize(new Dimension(945, 1020));
    driver.findElement(By.id("SearchRobot")).click();
    driver.findElement(By.id("SearchRobot")).sendKeys("t");
    driver.findElement(By.cssSelector("html")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("shadowAjax"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.id("buttonSearchRobot")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tr:nth-child(1) > td:nth-child(3)"));
      assert(elements.size() > 0);
    }
  }
}
