// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FormUpdatePremioTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC60AllFieldsUpdatePremio() {
    driver.get("http://localhost:8080/VORWERK/login.jsp");
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("demo@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Prova123");
    driver.findElement(By.cssSelector("input:nth-child(9)")).click();
    driver.findElement(By.id("tab-premi")).click();
    driver.findElement(By.id("tab-premi")).click();
    driver.findElement(By.linkText("details")).click();
    driver.findElement(By.id("updateNameAward")).click();
    driver.findElement(By.id("updateNameAward")).sendKeys("Caffettier");
    driver.findElement(By.id("updatePointsAward")).click();
    driver.findElement(By.id("updatePointsAward")).sendKeys("140");
    driver.findElement(By.id("updateDescriptionAward")).click();
    driver.findElement(By.id("updateDescriptionAward")).sendKeys("Con un motore al 100% in rame che imprime una potenza di 300W alle sue affilate lae in titanio, permette di ottenere sempre il grado di macinatura desiderato.");
    driver.findElement(By.id("updateQuantityAward")).click();
    driver.findElement(By.id("updateQuantityAward")).sendKeys("1");
    driver.findElement(By.id("updateInserisciAward")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert-success"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".align-self-start")).click();
  }
}
