// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegistrationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC10NoFieldsRegistration() {
    driver.get("http://localhost:8080/VORWERK/account/registrazione.jsp");
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    assertThat(driver.switchTo().alert().getText(), is("Il campo dell\'email deve essere compilato"));
  }
  @Test
  public void tC11OnlyEmail() {
    driver.get("http://localhost:8080/VORWERK/account/registrazione.jsp");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("vin@gmail.com");
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    assertThat(driver.switchTo().alert().getText(), is("Il campo della password deve essere compilato"));
  }
  @Test
  public void tC12OnlyEmailandPassword() {
    driver.get("http://localhost:8080/VORWERK/account/registrazione.jsp");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("vin@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Prova123");
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    assertThat(driver.switchTo().alert().getText(), is("Il campo della data di nascita deve essere compilato"));
  }
  @Test
  public void tC13AllFields() {
    driver.get("http://localhost:8080/VORWERK/account/registrazione.jsp");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("vincenzo8189@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Prova123");
    driver.findElement(By.id("data_di_nascita")).click();
    driver.findElement(By.id("data_di_nascita")).sendKeys("1999-05-31");
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tC140FormatEmailException() {
    driver.get("http://localhost:8080/VORWERK/account/registrazione.jsp");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("vincenzo8189@gmail.c");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Prova123");
    driver.findElement(By.id("data_di_nascita")).click();
    driver.findElement(By.id("data_di_nascita")).sendKeys("1999-05-31");
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tC141FormatEmailException() {
    driver.get("http://localhost:8080/VORWERK/account/registrazione.jsp");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("vincenzo8189@gmail.comm");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Prova123");
    driver.findElement(By.id("data_di_nascita")).click();
    driver.findElement(By.id("data_di_nascita")).sendKeys("1999-05-31");
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tC142EmailExistsException() {
    driver.get("http://localhost:8080/VORWERK/login.jsp");
    driver.findElement(By.linkText("Registrati")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("demo@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Prova123");
    driver.findElement(By.id("data_di_nascita")).click();
    driver.findElement(By.id("data_di_nascita")).sendKeys("1999-05-31");
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tC150FormatPasswordException() {
    driver.get("http://localhost:8080/VORWERK/account/registrazione.jsp");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("vin@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("prova123");
    driver.findElement(By.id("data_di_nascita")).click();
    driver.findElement(By.id("data_di_nascita")).sendKeys("1999-05-31");
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tC151FormatPasswordException() {
    driver.get("http://localhost:8080/VORWERK/account/registrazione.jsp");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("vin@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Provalbc");
    driver.findElement(By.id("data_di_nascita")).click();
    driver.findElement(By.id("data_di_nascita")).sendKeys("1999-05-31");
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tC152FormatPasswordException() {
    driver.get("http://localhost:8080/VORWERK/account/registrazione.jsp");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("vin@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Prova12");
    driver.findElement(By.id("data_di_nascita")).click();
    driver.findElement(By.id("data_di_nascita")).sendKeys("1999-05-31");
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tC153FormatPasswordException() {
    driver.get("http://localhost:8080/VORWERK/account/registrazione.jsp");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("vin@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Prova123Prova123Prova");
    driver.findElement(By.id("data_di_nascita")).click();
    driver.findElement(By.id("data_di_nascita")).sendKeys("1999-05-31");
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tC154FormatPasswordException() {
    driver.get("http://localhost:8080/VORWERK/account/registrazione.jsp");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("vin@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("PROVA123");
    driver.findElement(By.id("data_di_nascita")).click();
    driver.findElement(By.id("data_di_nascita")).sendKeys("1999-05-31");
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tC160FormatDataDiNascitaException() {
    driver.get("http://localhost:8080/VORWERK/account/registrazione.jsp");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("vin@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Prova123");
    driver.findElement(By.id("data_di_nascita")).click();
    driver.findElement(By.id("data_di_nascita")).sendKeys("2003-05-31");
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tC161FormatDataDiNascitaException() {
    driver.get("http://localhost:8080/VORWERK/account/registrazione.jsp");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("vin@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Prova123");
    driver.findElement(By.id("data_di_nascita")).click();
    driver.findElement(By.id("data_di_nascita")).sendKeys("2003/05/31");
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
      assert(elements.size() > 0);
    }
  }
}
